### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by zpxlz** [bytedance/vArmor-ebpf#3]
make vet 后会报错误：
vet: pkg/bpfenforcer/enforcer_test.go:32:14: undefined: NewBpfEnforcer
make: *** [Makefile:44: vet] Error 1

删除 [/pkg/bpfenforcer/enforcer.go](https://github.com/bytedance/vArmor-ebpf/blob/main/pkg/bpfenforcer/enforcer.go) 中 import "C" 就正常了。

**Comment by Danny-Wei** [comment]
感谢，已经 fix
